# Generated by Django 5.2.8 on 2025-12-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_document_is_public_document_share_token_activeeditor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
