# Generated by Django 5.2.8 on 2025-12-13 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_alter_document_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='auto_save_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='last_auto_save',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
